// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const ConsumerKeysSchema = z.object({
  id: z.string().uuid(),
  encryptedKey: z.string(),
  nonce: z.string(),
  receiverId: z.string().uuid(),
  senderId: z.string().uuid().nullable().optional(),
  orgId: z.string().uuid(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TConsumerKeys = z.infer<typeof ConsumerKeysSchema>;
export type TConsumerKeysInsert = Omit<z.input<typeof ConsumerKeysSchema>, TImmutableDBKeys>;
export type TConsumerKeysUpdate = Partial<Omit<z.input<typeof ConsumerKeysSchema>, TImmutableDBKeys>>;
