// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const ConsumerSecretsSchema = z.object({
  id: z.string().uuid(),
  type: z.string(),
  secretNameCiphertext: z.string(),
  secretNameIV: z.string(),
  secretNameTag: z.string(),
  secretFieldOneCiphertext: z.string(),
  secretFieldOneIV: z.string(),
  secretFieldOneTag: z.string(),
  secretFieldTwoCiphertext: z.string(),
  secretFieldTwoIV: z.string(),
  secretFieldTwoTag: z.string(),
  secretFieldThreeCiphertext: z.string(),
  secretFieldThreeIV: z.string(),
  secretFieldThreeTag: z.string(),
  secretFieldFourCiphertext: z.string(),
  secretFieldFourIV: z.string(),
  secretFieldFourTag: z.string(),
  skipMultilineEncoding: z.boolean().default(false).nullable().optional(),
  algorithm: z.string().default("aes-256-gcm"),
  keyEncoding: z.string().default("utf8"),
  metadata: z.unknown().nullable().optional(),
  userId: z.string().uuid(),
  orgId: z.string().uuid(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TConsumerSecrets = z.infer<typeof ConsumerSecretsSchema>;
export type TConsumerSecretsInsert = Omit<z.input<typeof ConsumerSecretsSchema>, TImmutableDBKeys>;
export type TConsumerSecretsUpdate = Partial<Omit<z.input<typeof ConsumerSecretsSchema>, TImmutableDBKeys>>;
