// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const SecretScanningSourcesSchema = z.object({
  id: z.string().uuid(),
  name: z.string(),
  description: z.string().nullable().optional(),
  type: z.string(),
  config: z.unknown(),
  connectionId: z.string().uuid().nullable().optional(),
  projectId: z.string(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TSecretScanningSources = z.infer<typeof SecretScanningSourcesSchema>;
export type TSecretScanningSourcesInsert = Omit<z.input<typeof SecretScanningSourcesSchema>, TImmutableDBKeys>;
export type TSecretScanningSourcesUpdate = Partial<Omit<z.input<typeof SecretScanningSourcesSchema>, TImmutableDBKeys>>;
