// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const SecretScanningTargetsSchema = z.object({
  id: z.string().uuid(),
  externalId: z.string(),
  name: z.string(),
  type: z.string(),
  sourceId: z.string().uuid(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TSecretScanningTargets = z.infer<typeof SecretScanningTargetsSchema>;
export type TSecretScanningTargetsInsert = Omit<z.input<typeof SecretScanningTargetsSchema>, TImmutableDBKeys>;
export type TSecretScanningTargetsUpdate = Partial<Omit<z.input<typeof SecretScanningTargetsSchema>, TImmutableDBKeys>>;
